name = "Nesquate's Server Modpack"
author = "Nesquate"
version = "s1-2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "75718badaca4f07b0e36d73d924cba72436d05bcc8256deb95b8e9d0387a8fb6"

[versions]
fabric = "0.14.17"
minecraft = "1.19.3"
