name = "Nesquate's Server Modpack"
author = "Nesquate"
version = "s1-3.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d505ab1063e059ee3ccc5be5183bdfcecd13ce434344a8ef95b970c97876fdbd"

[versions]
fabric = "0.14.17"
minecraft = "1.19.3"
