name = "Nesquate's Server Modpack"
author = "Nesquate"
version = "s1-1.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5be86062ae4174cc20ec94667b253046d00d246b6bb58e7a4e780089884a9f4c"

[versions]
fabric = "0.14.17"
minecraft = "1.19.3"
